version: '3.7'
services:

  symfony_php_fpm:
    container_name: symfony_php_fpm_1
    build:
      context: ./docker/php_fpm/
    working_dir: /var/www/symfony
    volumes:
      - ./application:/var/www/symfony
      - ./docker/php_fpm/configs/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      XDEBUG_CONFIG: "remote_enable=1 remote_host=docker.for.mac.localhost remote_port=9370 idekey=PHPSTORM"
      PHP_IDE_CONFIG: "serverName=localhost"
      COMPOSER_HOME: "/tmp"
      COMPOSER_MEMORY_LIMIT: -1
    networks:
      symfony_net:
        ipv4_address: 172.16.70.13

  symfony_nginx:
    container_name: symfony_nginx_1
    image: nginx:1.15
    working_dir: /var/www/symfony
    volumes:
      - ./application:/var/www/symfony
      - ./docker/nginx/configs/vhost.local.conf:/etc/nginx/conf.d/symfony.conf
      - ./docker/nginx/configs/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 7014:80
    networks:
      symfony_net:
        ipv4_address: 172.16.70.14

  symfony_mysql:
    container_name: symfony_mysql_1
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    expose:
      - 3306
    ports:
      - 7011:3306
    networks:
      symfony_net:
        ipv4_address: 172.16.70.11

  symfony_redis:
    container_name: symfony_redis_1
    image: redis:latest
    expose:
      - 6379
    networks:
      symfony_net:
        ipv4_address: 172.16.70.15
networks:
  symfony_net:
    name: symfony_net
    ipam:
      driver: default
      config:
        - subnet: 172.16.70.0/24

volumes:
  dbdata:
